return {
  -- {
  --   "glepnir/lspsaga.nvim",
  --   event = "LspAttach",
  --   config = function()
  --     require("lspsaga").setup({
  --       ui = {
  --         border = "rounded", -- Rounded borders for floating windows
  --       },
  --       diagnostic = {
  --         show_code_action = true, -- Disable action hints in diagnostics
  --       },
  --       code_action = {
  --         keys = {
  --           quit = "q",    -- Key to quit the code action menu
  --           exec = "<CR>", -- Key to execute the selected action
  --         },
  --       },
  --     })
  --   end,
  --   dependencies = { { "nvim-tree/nvim-web-devicons" } },
  -- },
}
